In [1]:
import numpy as np
from numpy import genfromtxt 
import pandas as pd

In [33]:
# 0 -> benign , 1 -> malicious  train data
feature=genfromtxt('train_34.csv', delimiter=',', usecols=(i for i in range(0,34)),dtype=float,skip_header=1)
class_value=genfromtxt('train_34.csv', delimiter=',', usecols=(-1), dtype=str, skip_header=1)
print(feature)
print(class_value)

[[0. 0. 1. ... 1. 0. 0.]
 [1. 1. 0. ... 1. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 1. ... 1. 0. 0.]
 [1. 0. 1. ... 1. 0. 0.]
 [1. 0. 1. ... 1. 0. 0.]]
['1' '1' '1' ... '1' '1' '1']


In [31]:
feature

array([[0, 0, 1, ..., 1, 0, 0],
       [1, 1, 0, ..., 1, 0, 1],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 1, 0, 0],
       [1, 0, 1, ..., 1, 0, 0],
       [1, 0, 1, ..., 1, 0, 0]])

In [3]:
# import testing data 
feature_test=genfromtxt('test_34.csv', delimiter=',', usecols=(i for i in range(0,34)),dtype=float,skip_header=1)
class_value_test=genfromtxt('test_34.csv', delimiter=',', usecols=(-1), dtype=str, skip_header=1)
print(feature)
print(class_value)

[[0. 0. 1. ... 1. 0. 0.]
 [1. 1. 0. ... 1. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 1. ... 1. 0. 0.]
 [1. 0. 1. ... 1. 0. 0.]
 [1. 0. 1. ... 1. 0. 0.]]
['1' '1' '1' ... '1' '1' '1']


In [4]:
# train data
feature= feature.astype(int)
class_value= class_value.astype(int)
# test data
feature_test= feature_test.astype(int)
class_value_test= class_value_test.astype(int)

# svm 

In [5]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,f1_score


In [6]:
#Create a svm Classifier
clf_svm = SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf_svm.fit(feature, class_value)

#Predict the response for test dataset
y_pred_svm = clf_svm.predict(feature_test)

In [7]:
print(y_pred_svm)

[1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 0 1 1 1 1 1 0 1 1 1
 1 1 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 1
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 0 0 0 0 1 1
 1 1 0 1 1 1 1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]


In [8]:
accuracy_score(class_value_test,y_pred_svm)

0.9095477386934674

In [9]:
f1_score(class_value_test,y_pred_svm)

0.9027027027027027

# RandomForestClassifier

In [10]:
from sklearn.ensemble import RandomForestClassifier
clf_rf = RandomForestClassifier(max_depth=2, random_state=0)
clf_rf.fit(feature, class_value)
y_pred_rf = clf_rf.predict(feature_test)

In [11]:
accuracy_score(class_value_test,y_pred_rf)

0.7537688442211056

In [12]:
f1_score(class_value_test,y_pred_rf)

0.6754966887417219

# GaussianNB

In [13]:
from sklearn.naive_bayes import GaussianNB
clf_nb = GaussianNB()
clf_nb.fit(feature, class_value)
y_pred_nb = clf_nb.predict(feature_test)

In [14]:
accuracy_score(class_value_test,y_pred_nb)

0.907035175879397

In [15]:
f1_score(class_value_test,y_pred_nb)

0.9053708439897697

# DecisionTreeClassifier

In [16]:
from sklearn.tree import DecisionTreeClassifier
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(feature, class_value)
y_pred_dt = clf_dt.predict(feature_test)

In [18]:
accuracy_score(class_value_test,y_pred_dt)

0.9547738693467337

In [19]:
f1_score(class_value_test,y_pred_dt)

0.9540816326530611

#  KNeighborsClassifier

In [20]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors=3)
clf_knn.fit(feature, class_value)
y_pred_knn = clf_knn.predict(feature_test)

In [21]:
accuracy_score(class_value_test,y_pred_knn)

0.6959798994974874

In [22]:
f1_score(class_value_test,y_pred_knn)

0.7650485436893204

#  BaggingClassifier

In [23]:
from sklearn.ensemble import BaggingClassifier
clf_bgg = BaggingClassifier(base_estimator=SVC(), n_estimators=10, random_state=0)
clf_bgg.fit(feature, class_value)
y_pred_bgg = clf_bgg.predict(feature_test)

In [24]:
accuracy_score(class_value_test,y_pred_bgg)

0.9447236180904522

In [25]:
f1_score(class_value_test,y_pred_bgg)

0.9427083333333334

In [27]:
print("svm: ", clf_svm.predict([[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0]]))
print("RF :", clf_rf.predict([[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0]]))
print("NB :", clf_nb.predict([[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0]]))
print("DT :", clf_dt.predict([[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0]]))
print("KNN :",clf_knn.predict([[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0]]))
print("Bagging :", clf_bgg.predict([[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0]]))

svm:  [0]
RF : [0]
NB : [0]
DT : [0]
KNN : [0]
Bagging : [0]
