In [1]:
import numpy as np
from numpy import genfromtxt 
import pandas as pd

In [2]:
# 0 -> benign , 1 -> malicious  train data
feature=genfromtxt('train.csv', delimiter=',', usecols=(i for i in range(0,22)),dtype=float,skip_header=1)
class_value=genfromtxt('train.csv', delimiter=',', usecols=(-1), dtype=str, skip_header=1)
print(feature)
print(class_value)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['1' '1' '1' ... '1' '1' '1']


In [3]:
# import testing data 
feature_test=genfromtxt('test.csv', delimiter=',', usecols=(i for i in range(0,22)),dtype=float,skip_header=1)
class_value_test=genfromtxt('test.csv', delimiter=',', usecols=(-1), dtype=str, skip_header=1)
print(feature)
print(class_value)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['1' '1' '1' ... '1' '1' '1']


In [ ]:
# train data
feature= feature.astype(int)
class_value= class_value.astype(int)
# test data
feature_test= feature_test.astype(int)
class_value_test= class_value_test.astype(int)

# svm 

In [7]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,f1_score


In [9]:
#Create a svm Classifier
clf_svm = SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf_svm.fit(feature, class_value)

#Predict the response for test dataset
y_pred_svm = clf_svm.predict(feature_test)

In [10]:
print(y_pred_svm)

[1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1 1
 1 1 0 1 1 1 1 0 1 0 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 0 1 0 1 0 1 1 1 0 0
 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1 0 1 1 1 0 1 1 1
 0 0 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1
 1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 0 0 1 0 1 0 1 0 0 0 0 1 1
 1 1 0 0 1 1 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]


In [11]:
accuracy_score(class_value_test,y_pred_svm)

0.8190954773869347

In [12]:
f1_score(class_value_test,y_pred_svm)

0.7882352941176471

# RandomForestClassifier

In [13]:
from sklearn.ensemble import RandomForestClassifier
clf_rf = RandomForestClassifier(max_depth=2, random_state=0)
clf_rf.fit(feature, class_value)
y_pred_rf = clf_rf.predict(feature_test)

In [14]:
accuracy_score(class_value_test,y_pred_rf)

0.7311557788944724

In [15]:
f1_score(class_value_test,y_pred_rf)

0.6372881355932204

# GaussianNB

In [16]:
from sklearn.naive_bayes import GaussianNB
clf_nb = GaussianNB()
clf_nb.fit(feature, class_value)
y_pred_nb = clf_nb.predict(feature_test)

In [17]:
accuracy_score(class_value_test,y_pred_nb)

0.8442211055276382

In [18]:
f1_score(class_value_test,y_pred_nb)

0.8287292817679558

# DecisionTreeClassifier

In [38]:
from sklearn.tree import DecisionTreeClassifier
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(feature, class_value)
y_pred_dt = clf_dt.predict(feature_test)

In [47]:
test = clf_dt.predict([[1,0,0,0,0,1,0,0,1,0,0,1,1,1,0,1,0,0,0,0,0,0]])
print(test)

[1]


In [35]:
accuracy_score(class_value_test,y_pred_dt)

0.9447236180904522

In [36]:
f1_score(class_value_test,y_pred_dt)

0.9430051813471502

#  KNeighborsClassifier

In [22]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors=3)
clf_knn.fit(feature, class_value)
y_pred_knn = clf_knn.predict(feature_test)

In [23]:
accuracy_score(class_value_test,y_pred_knn)

0.6306532663316583

In [24]:
f1_score(class_value_test,y_pred_knn)

0.7302752293577982

#  BaggingClassifier

In [25]:
from sklearn.ensemble import BaggingClassifier
clf_bgg = BaggingClassifier(base_estimator=SVC(), n_estimators=10, random_state=0)
clf_bgg.fit(feature, class_value)
y_pred_bgg = clf_bgg.predict(feature_test)

In [26]:
accuracy_score(class_value_test,y_pred_bgg)

0.9396984924623115

In [27]:
f1_score(class_value_test,y_pred_bgg)

0.93717277486911